WebApp/Controllers/BuyTicketController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class BuyTicketController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Pay()
        {
            return View();
        }
    }
}

WebApp/Views/BuyTicket/Index.cshtml
@{
    ViewData["Title"] = "Inscrição no Evento";
}

<div class="d-flex justify-content-center" style="padding-top: 10vh;">
    <div style="max-width: 600px; width: 100%;">
        <h2 class="text-center"><strong>Inscrição</strong></h2>
        <form method="post" class="mt-3">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="name" placeholder="John Doe" required>
                <label for="name">Nome</label>
            </div>
            <div class="form-floating mb-3">
                <input type="email" class="form-control" id="email" placeholder="name@example.com" required>
                <label for="email">Email</label>
            </div>
            <div class="d-flex justify-content-center mt-4">
                <a href="@Url.Action("Pay", "BuyTicket")" class="btn btn-outline-dark">Inscrever-me</a>
            </div>
        </form>
    </div>
</div>

WebApp/Views/BuyTicket/Pay.cshtml
@{
    ViewData["Title"] = "Pagamento";
}

<div class="d-flex justify-content-center" style="padding-top: 10vh;">
    <div style="max-width: 600px; width: 100%;">
        <h2 class="text-center"><strong>Pagamento e Faturação</strong></h2>
        <form class="mt-3">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="nome" placeholder="John Doe">
                <label for="nome">Nome</label>
            </div>
            <div class="form-floating mb-3">
                <input type="email" class="form-control" id="email" placeholder="email@email.com">
                <label for="email">Email</label>
            </div>
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="nif" placeholder="NIF">
                <label for="nif">NIF</label>
            </div>
            <div class="mb-3">
                <h5>Método de Pagamento</h5>
                <div class="accordion" id="accordionExample">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Cartão de Crédito/Débito
                            </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="cardNumber" placeholder="1234 5678 9012 3456">
                                    <label for="cardNumber">Número do Cartão</label>
                                </div>
                                <div class="d-flex gap-3 mb-3">
                                    <div class="form-floating flex-fill">
                                        <input type="text" class="form-control" id="validity" placeholder="01/26">
                                        <label for="validity">Validade</label>
                                    </div>
                                    <div class="form-floating flex-fill">
                                        <input type="text" class="form-control" id="CCV" placeholder="000">
                                        <label for="CCV">CCV</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingTwo">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                MBWay
                            </button>
                        </h2>
                        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="phoneNumber" placeholder="987 654 321">
                                    <label for="phoneNumber">Número de Telemóvel</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingThree">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                Multibanco
                            </button>
                        </h2>
                        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                Será gerada uma referência MB válida por 8 horas. O envio será feito quando for confirmado o pagamento.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="billingAddress" placeholder="Rua Exemplo, 123">
                <label for="billingAddress">Endereço de Faturação</label>
            </div>
            <div class="d-flex gap-3 mb-3">
                <div class="form-floating flex-fill">
                    <input type="text" class="form-control" id="city" placeholder="Cidade">
                    <label for="city">Cidade</label>
                </div>
                <div class="form-floating flex-fill">
                    <input type="text" class="form-control" id="postalCode" placeholder="0000-000">
                    <label for="postalCode">Código Postal</label>
                </div>
            </div>
            <div class="d-flex justify-content-center mt-4">
                <a href="@Url.Action("Index", "Home")" class="btn btn-outline-dark">Confirmar Pagamento</a>
            </div>
        </form>
    </div>
</div>